#!/bin/sh
[ $ACTION = "step" ]    && logger -t ntpd Time set, stratum=$stratum interval=$poll_interval offset=$offset
[ $ACTION = "stratum" ] && logger -t ntpd Stratum change, stratum=$stratum interval=$poll_interval offset=$offset && if [ $(echo "$offset < 0.1" | bc) -eq 1 ]; then if [ ! -e '/tmp/fsk-ntp-sync' ]; then echo `date` > /tmp/fsk-ntp-sync; fi fi
